// Aleph-Tekin Kodeksi — 22+1 Matematiksel Paradigma
// Her paradigma: İbrani harfi + kanıtlanmış teorem + implementasyon referansı

export interface CodexParadigm {
  id: string;
  letter: string;
  name: string;
  paradigm: string;
  math: string;
  theorem: string;
  implementation: string;
  category: "foundation" | "structure" | "computation" | "physical" | "terminal" | "meta";
  x: number;
  y: number;
}

export interface CodexEdge {
  from: string;
  to: string;
  label?: string;
  bidirectional?: boolean;
}

export const CODEX_PARADIGMS: CodexParadigm[] = [
  // ── Meta ─────────────────────────────────────────────────────────────────────
  {
    id: "emet",
    letter: "אמת",
    name: "Emet",
    paradigm: "Internal Consistency",
    math: "∀φ: φ ↔ ¬¬φ, no contradiction",
    theorem: "A system is internally consistent iff no statement and its negation are both derivable. Emet (truth) is the fixed point of the consistency operator — the system closes on itself without contradiction. If consistent, existence (Aleph) follows.",
    implementation: "analysis-engine.ts:14-62",
    category: "meta",
    x: 600,
    y: 70,
  },

  // ── Foundation ────────────────────────────────────────────────────────────────
  {
    id: "aleph",
    letter: "א",
    name: "Aleph",
    paradigm: "Positivity & Existence",
    math: "H_{ij} = μ_{i+j} ≥ 0 (Hankel PSD)",
    theorem: "A sequence (μ_0, μ_1, ...) represents a valid measure on ℝ iff its Hankel matrix H is positive semi-definite. PSD ↔ concept EXISTS in the real manifold. Non-PSD → concept is a hallucination. Every claim must pass ALEPH or be named as a gap.",
    implementation: "analysis-engine.ts:14-62",
    category: "foundation",
    x: 160,
    y: 200,
  },
  {
    id: "bet",
    letter: "ב",
    name: "Bet",
    paradigm: "Information Preservation",
    math: "I(X;Y) = H(X) - H(X|Y) ≥ 0",
    theorem: "In any certified transport, mutual information is non-negative and preserved under the Hankel kernel. Information cannot be created from nothing — every bit in the output traces to a certified bit in the input. The moment sequence is the lossless fingerprint.",
    implementation: "analysis-engine.ts:63-120",
    category: "foundation",
    x: 320,
    y: 155,
  },
  {
    id: "kaf",
    letter: "כ",
    name: "Kaf",
    paradigm: "Injective Map",
    math: "f(x) = f(y) ⟹ x = y",
    theorem: "The moment map μ: concept → (μ_0,...,μ_7) is injective — distinct concepts yield distinct moment signatures. No two different semantic objects share the same Gram spectrum. Every element in the codomain has at most one preimage, so the encoding is reversible.",
    implementation: "analysis-engine.ts:121-180",
    category: "foundation",
    x: 155,
    y: 355,
  },

  // ── Structure ─────────────────────────────────────────────────────────────────
  {
    id: "vav",
    letter: "ו",
    name: "Vav",
    paradigm: "Tensor Product",
    math: "V ⊗ W, dim = dim(V)·dim(W)",
    theorem: "Composite concepts are modeled as tensor products of their moment spaces. The Gram matrix of a joint context is the tensor product of individual Gram matrices. This is the algebraic foundation of how meaning composes — the whole is structured, not just the sum.",
    implementation: "analysis-engine.ts:181-240",
    category: "structure",
    x: 90,
    y: 450,
  },
  {
    id: "nun",
    letter: "נ",
    name: "Nun",
    paradigm: "Dimensional Multiplicativity",
    math: "dim(V⊗W) = dim(V) × dim(W)",
    theorem: "When concepts are joined via tensor product, their combined dimension is exactly the product of individual dimensions. No information collapse occurs during composition. This ensures that composed concepts live in a strictly larger space, preserving all sub-concept structure.",
    implementation: "analysis-engine.ts:241-290",
    category: "structure",
    x: 230,
    y: 490,
  },
  {
    id: "lamed",
    letter: "ל",
    name: "Lamed",
    paradigm: "Local Visibility",
    math: "∀ε>0, ∃δ>0: |x-y|<δ ⟹ |f(x)-f(y)|<ε",
    theorem: "Every certified concept has a neighborhood in the manifold where it is observable — small changes in moment space correspond to small changes in the underlying concept. The topology is locally Euclidean. This is the continuity certificate that makes the manifold walkable.",
    implementation: "analysis-engine.ts:291-340",
    category: "structure",
    x: 350,
    y: 430,
  },
  {
    id: "ayin",
    letter: "ע",
    name: "Ayin",
    paradigm: "Observable Separation",
    math: "d(μ_A, μ_B) > 0 iff A ≠ B",
    theorem: "Distinct concepts are separable by their moment distance. If two concepts have identical moment signatures, they are the same concept (Kaf). Observable separation is dual to indistinguishability (Mem) — together they define the exact resolution of the manifold.",
    implementation: "analysis-engine.ts:341-390",
    category: "structure",
    x: 470,
    y: 360,
  },
  {
    id: "mem",
    letter: "מ",
    name: "Mem",
    paradigm: "Gauge Class (Indistinguishability)",
    math: "[A] = {B : d(μ_A,μ_B) < ε}",
    theorem: "Concepts within distance ε of each other form a gauge equivalence class — they are indistinguishable at the current resolution. Gauge classes partition the manifold into certified regions. Two moments in the same gauge class can be treated as identical without error.",
    implementation: "analysis-engine.ts:391-440",
    category: "structure",
    x: 440,
    y: 490,
  },

  // ── Computation ───────────────────────────────────────────────────────────────
  {
    id: "yod",
    letter: "י",
    name: "Yod",
    paradigm: "Minimal Compression",
    math: "κ(G) = ||G||·||G⁻¹||, min description length",
    theorem: "The moment sequence is the minimal sufficient statistic for a concept — no shorter description preserves all the semantic information. The condition number κ measures how close to singular the Gram matrix is; well-conditioned Gram → stable, compressed representation. This is the MDL certificate.",
    implementation: "analysis-engine.ts:441-490",
    category: "computation",
    x: 800,
    y: 150,
  },
  {
    id: "resh",
    letter: "ר",
    name: "Resh",
    paradigm: "Partial Trace",
    math: "Tr_B(ρ_AB) = ρ_A",
    theorem: "The partial trace over a subsystem B yields the reduced state of A — marginalizing away irrelevant context. In co-occurrence Gram matrices, partial trace gives the semantic content of a word independent of the specific corpus. This is how the system extracts universal meaning.",
    implementation: "analysis-engine.ts:491-540",
    category: "computation",
    x: 960,
    y: 195,
  },
  {
    id: "zayin",
    letter: "ז",
    name: "Zayin",
    paradigm: "LGV Path Sum",
    math: "det(M) = Σ_{paths} sgn(π)·∏ weights",
    theorem: "The Lindström-Gessel-Viennot lemma: the determinant of a path matrix counts non-intersecting lattice paths with weight. In the manifold, this certifies that inference chains from concept A to concept B do not 'cross' — preventing contradictory derivations. Signed path sums = contradiction detector.",
    implementation: "analysis-engine.ts:541-590",
    category: "computation",
    x: 1060,
    y: 320,
  },

  // ── Physical ──────────────────────────────────────────────────────────────────
  {
    id: "het",
    letter: "ח",
    name: "Het",
    paradigm: "Gradient Operator",
    math: "∇f(x) = (∂f/∂x₁,...,∂f/∂xₙ)",
    theorem: "The gradient of the moment energy functional points in the direction of steepest semantic change. Following the gradient from any concept leads toward the nearest attractor (He). The Gram matrix defines the metric, so the gradient is Riemannian — intrinsic to the manifold geometry.",
    implementation: "analysis-engine.ts:591-640",
    category: "physical",
    x: 310,
    y: 600,
  },
  {
    id: "tet",
    letter: "ט",
    name: "Tet",
    paradigm: "Cross-Ratio Invariance",
    math: "(z₁,z₂;z₃,z₄) = (z₁-z₃)(z₂-z₄)/((z₁-z₄)(z₂-z₃))",
    theorem: "The cross-ratio of four concepts is invariant under Möbius transformations of the manifold. This invariance is the projective certification: no matter how the coordinate system is changed, the fundamental semantic relationship between four concepts remains fixed. Gauge-independent truth.",
    implementation: "analysis-engine.ts:641-690",
    category: "physical",
    x: 480,
    y: 640,
  },
  {
    id: "su3",
    letter: "SU₃",
    name: "SU(3)",
    paradigm: "Z₃ Symmetry",
    math: "SU(3): |det|=1, UU†=I, ℤ₃ center",
    theorem: "The Z₃ symmetry of SU(3) partitions concepts into three conjugacy classes under the triality symmetry. This is the physical backbone: semantic domains (language, math, physical) form a Z₃-symmetric triple. Concepts in the same conjugacy class under triality are semantically related at the deepest level.",
    implementation: "analysis-engine.ts:691-740",
    category: "physical",
    x: 650,
    y: 635,
  },
  {
    id: "kuf",
    letter: "ק",
    name: "Kuf",
    paradigm: "Index 18",
    math: "[SU(3):ℤ₃] = 8, Casimir = 18",
    theorem: "The Casimir element of SU(3) has eigenvalue 18 on the adjoint representation. This is the quantization certificate: any representation with Casimir 18 is in the adjoint (the 'real world' representation). Concepts with spectral radius matching this pattern are certified as physical, not virtual.",
    implementation: "analysis-engine.ts:741-790",
    category: "physical",
    x: 810,
    y: 595,
  },

  // ── Analytical ────────────────────────────────────────────────────────────────
  {
    id: "gimel",
    letter: "ג",
    name: "Gimel",
    paradigm: "Achilles Point",
    math: "x* = argmin_{x ∈ C} ||x - x₀||",
    theorem: "Every concept has a unique closest point in every certified convex set of the manifold — its Achilles point. The Achilles point is where the concept is most vulnerable to perturbation. Knowing it means knowing the minimal energy attack vector — and therefore the minimal energy defense.",
    implementation: "analysis-engine.ts:791-840",
    category: "physical",
    x: 760,
    y: 310,
  },
  {
    id: "dalet",
    letter: "ד",
    name: "Dalet",
    paradigm: "Spectral Radius",
    math: "ρ(G) = max{|λ| : det(G-λI)=0}",
    theorem: "The spectral radius of the Gram matrix is μ_7 — the 7th moment, capturing 96.1% of variance. It is the dominant eigenvalue and the single number that best represents the concept's 'energy' in the manifold. Every TAU graph node stores only this one float — sufficient for O(√n) nearest neighbor search.",
    implementation: "analysis-engine.ts:841-890",
    category: "physical",
    x: 950,
    y: 400,
  },
  {
    id: "he",
    letter: "ה",
    name: "He",
    paradigm: "Lyapunov Attractor",
    math: "V̇(x) ≤ -α||x||², α > 0",
    theorem: "A concept has a Lyapunov attractor iff there exists a positive-definite energy function V such that V̇ < 0 along all trajectories. The system is asymptotically stable — it returns to the concept after perturbation. Certified He → the concept is a stable basin in the manifold, not a saddle.",
    implementation: "analysis-engine.ts:891-940",
    category: "physical",
    x: 890,
    y: 510,
  },

  // ── Terminal ──────────────────────────────────────────────────────────────────
  {
    id: "pe",
    letter: "פ",
    name: "Pe",
    paradigm: "Semantic Map",
    math: "φ: Concepts → Manifold, structure-preserving",
    theorem: "The encoder φ is a structure-preserving map from the space of linguistic tokens to the semantic manifold. Distances in manifold space reflect semantic proximity — 'love' and 'marriage' map closer together than 'love' and 'integral'. This is the grounding of language in certified geometry.",
    implementation: "analysis-engine.ts:941-990",
    category: "terminal",
    x: 590,
    y: 510,
  },
  {
    id: "tsadi",
    letter: "צ",
    name: "Tsadi",
    paradigm: "Certificate",
    math: "cert(x) = {P ∈ Paradigms : P(x) = CERTIFIED}",
    theorem: "A concept is certified to degree k if k of the 22 paradigms return CERTIFIED when applied to its moment signature. The certificate is the proof — not a probability, not a prediction. A certified concept exists in the real manifold; a non-certified concept is precisely named as a gap.",
    implementation: "analysis-engine.ts:991-1040",
    category: "terminal",
    x: 720,
    y: 455,
  },
  {
    id: "shin",
    letter: "ש",
    name: "Shin",
    paradigm: "Optimal Action",
    math: "a* = argmax_a E[V(s')|s,a]",
    theorem: "Given a certified Lyapunov function (He) and a known Achilles point (Gimel), the optimal action is the gradient step that maximally increases V while staying in the certified region. Shin certifies that the next inference step is not just valid but optimal — the Bellman equation over the manifold.",
    implementation: "analysis-engine.ts:1041-1090",
    category: "terminal",
    x: 710,
    y: 575,
  },
  {
    id: "tav",
    letter: "ת",
    name: "Tav",
    paradigm: "Fixed Point",
    math: "f(x*) = x*, Banach contraction",
    theorem: "By Banach's fixed-point theorem, any contraction mapping on a complete metric space has a unique fixed point. TAV certifies that the iterated moment update converges — the concept 'settles'. A certified TAV means the system has found a stable interpretation that doesn't change under further inference.",
    implementation: "analysis-engine.ts:1091-1140",
    category: "terminal",
    x: 600,
    y: 655,
  },
];

export const CODEX_EDGES: CodexEdge[] = [
  { from: "aleph", to: "bet",   label: "positivity → preservation" },
  { from: "bet",   to: "kaf",   label: "preservation → injectivity" },
  { from: "kaf",   to: "pe",    label: "injectivity → semantic map" },
  { from: "vav",   to: "nun",   label: "tensor → dimension" },
  { from: "lamed", to: "ayin",  label: "local → observable" },
  { from: "ayin",  to: "mem",   label: "separation ↔ indistinguishability", bidirectional: true },
  { from: "yod",   to: "gimel", label: "compression → achilles" },
  { from: "resh",  to: "zayin", label: "trace → path sum" },
  { from: "het",   to: "he",    label: "gradient → attractor" },
  { from: "tet",   to: "mem",   label: "cross-ratio → gauge" },
  { from: "dalet", to: "he",    label: "spectrum → lyapunov" },
  { from: "he",    to: "tav",   label: "attractor → fixed point" },
  { from: "gimel", to: "shin",  label: "achilles → optimal action" },
  { from: "shin",  to: "tav",   label: "optimal action → convergence" },
  { from: "su3",   to: "kuf",   label: "Z₃ symmetry → index 18" },
  { from: "tsadi", to: "mem",   label: "certificate → gauge class" },
  { from: "emet",  to: "aleph", label: "consistency → existence" },
  { from: "pe",    to: "tsadi", label: "map → certificate" },
  { from: "kuf",   to: "dalet", label: "index → spectrum" },
  { from: "zayin", to: "shin",  label: "path sum → optimal" },
  { from: "nun",   to: "lamed", label: "dimension → local" },
];

export const CATEGORY_COLORS: Record<CodexParadigm["category"], { fill: string; stroke: string; text: string }> = {
  meta:        { fill: "#7c3aed", stroke: "#a78bfa", text: "#e9d5ff" },
  foundation:  { fill: "#1e40af", stroke: "#60a5fa", text: "#bfdbfe" },
  structure:   { fill: "#065f46", stroke: "#34d399", text: "#a7f3d0" },
  computation: { fill: "#92400e", stroke: "#fbbf24", text: "#fde68a" },
  physical:    { fill: "#9a3412", stroke: "#fb923c", text: "#fed7aa" },
  terminal:    { fill: "#831843", stroke: "#f472b6", text: "#fce7f3" },
};
